- iocage_lib/ioc_upgrade.py
Lost the original PR, but this patch ensures that freebsd-update args are correctly split
> Correctly construct arguments for freebsd-update

- iocage_lib/ioc_json.py
- iocage_lib/ioc_start.py
fix #5
- Allow use of new allow.nfsd parameter with iocage's `allow_nfsd=1`
> allow_nfsd new param

- iocage_lib/ioc_exec.py
- iocage_lib/ioc_upgrade.py
Just test for non-emptiness before making it available to exec and upgrade processes
fix #7
> Do not place empty HTTP_PROXY in env

- iocage_lib/ioc_exceptions.py
from Alexander Leidinger, see
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269298
Fix collections vs collections.abc Iterable
fix #11
> fix collections vs Iterable

- iocage_lib/utils.py
- requirements.txt
- setup.py
I noticed that the Python 3.11 iocage-devel package has a missing dependency on`six`. Given it's only used in one place, and for compatibility with Python 2 which is no longer supported, remove it.
> Remove dependency on six

- .cirrus.yml
- tests/conftest.py
----
This fixes the Cirrus CI configuration to run functional tests.
Closes #23.
Main changes:
- Install rust, now required to build jsonschema
- Switch image to 14.1-RELEASE, 13.2 not being available anymore on GCP
- Switch default release in tests to 14.1, 12.2 not being available anymore
> Fix Cirrus CI

- iocage_lib/ioc_common.py
Fix #20: remaining `collections.Iterable` in `iocage_lib/ioc_common.py`
---
> Replace deprecated collections.Iterable by collections.abc.Iterable

- iocage_lib/iocage.py
Fixes #19 
Second change for the sake of clarity.
> Run pkg as interactive

- iocage_lib/ioc_json.py
Change to 'none' instead of 'auto', which can have unexpected effects on host's routing
fix #10
> change default for vnet_default_interface

- iocage_cli/df.py
- iocage_cli/snaplist.py
- iocage_lib/ioc_common.py
- iocage_lib/ioc_fstab.py
- iocage_lib/ioc_list.py
- iocage_lib/ioc_plugin.py
Hello!
In my pursuit of deepening knowledge about `FreeBSD jails`, a lot of people and books point to `iocage` as the way to go, so I checked the project. While doing so, I noticed usages of `list.insert(0, ...)`, which is a Python footgun, because despite the name, Python lists are more like arrays with optimized appends, not prepends, so such call incurs an O(n) runtime penalty.
I decided to grep the codebase for `.insert(` method calls and fix them in this pull request.
---
Remaining usages:
```
$ rg '\.insert\(' --glob='*.py'
doc/source/conf.py
21:sys.path.insert(0, os.path.abspath('.'))
tests/conftest.py
262:        cmd.insert(0, 'iocage')
iocage_lib/ioc_start.py
1753:                    rules.insert(1, f'{final_line}{rdrs}')
1763:                rules.insert(1, nat_rule)
```
were …
> Replace usages of `list.insert(0, ...)`

- .cirrus.yml
Hello @dgeo,
I propose a few more improvements to the Cirrus CI script. You can see the result on my fork.
If you can just enable the Cirrus CI app on this repo, it should work right away and we would get the corresponding checks on future pull requests, in addition to the unit test ones dones through Github Actions.
This commit brings the following improvements:
- get junit xml report for annotations in Github
- test with pkg and with pip packages
- use caches to reduce running time
----
> Improve Cirrus CI

- doc/source/advanced-use.rst
- iocage_cli/snaplist.py
- iocage_cli/snapremove.py
- iocage_cli/snapshot.py
- iocage_lib/iocage.py
- tests/conftest.py
- tests/data_classes.py
- tests/functional_tests/0018_snapshot_test.py
- tests/functional_tests/0019_list_snapshot_test.py
- tests/functional_tests/0020_remove_snapshot_test.py
Hello,
Okay so this is a proposal to close #18.
It brings:
- `iocage snaplist ALL` to list snapshots from all jails at once
- `iocage snapshot ALL -n <name>` to take a snapshot of all jails at once, with a common name. Intended for mass backup, upgrade or migration scenarios.
- `iocage snapremove ALL -n <name>` to remove such a common snapshot from all jails.
- `iocage snapremove <jail> -n ALL -f` to remove all snapshots from a jail. It requires `-f` or `--force`.
- These last two can be combined into `iocage snapremove ALL -n ALL -f` to remove all snapshots from all jails.
I provided some tests for all these features and an update for the documentation.
----
> Implement ALL target for snapshot, snaplist and snapremove

- iocage_lib/ioc_upgrade.py
This eliminates the dependency on github during upgrade.  It also makes it possible to upgrade to a release that does not have -RELEASE in the name.
Fixes #36
> During upgrade, use freebsd-update from an already-fetched release

- iocage.8
- iocage_cli/update.py
- iocage_lib/iocage.py
They work just like they do for iocage fetch.
> Add --server and --[no]verify options to iocage update

- README.md
- iocage_lib/ioc_check.py
fdescfs used to be useful to help Python more quickly close file descriptors before exec().  But for years, Python has been using closefrom() instead.  All versions of Python 3.9 and later do that.
Fixes #39
> Delete recommendations to mount fdescfs

- iocage_lib/ioc_start.py
- tests/data_classes.py
- tests/functional_tests/0004_start_test.py
Iocage currently expects interfaces to be specified in the nic:bridge format, where bridge cannot be none. This results in iocage always creating a bridge to which VNET jail epair interfaces are added as members.
In a scenario where the user wants jails to be isolated on the data-link layer (OSI layer 2 / Ethernet) and use the host as a router, this bridge is unnecessery. It can also result in illegitimate cross-jail traffic being allowed, since pf filtering on bridge interfaces is disabled by default on FreeBSD systems (net.link.bridge.pfil_bridge=0).
Closes #44
----
Passing CI job: https://cirrus-ci.com/task/6547222509125632
For some reason the CI run using python packages instead of pre-built `pkg` ones is broken (incl. on the master branch) and indefinitely hangs on …
> ioc_start.py: allow 'none' bridge in interfaces

- iocage_lib/ioc_fetch.py
- iocage_lib/ioc_plugin.py
This adds hardening measures while untaring archives fetched over the network (including FreeBSD tarballs and iocage plugins), as implemented by TrueNAS, see:
https://github.com/truenas/iocage/pull/358
This reduces the impact of intentionally malicious or accidentally broken archives.
Please note that users are still advised to only fetch from trusted sources and make use of TLS to prevent MITM attacks.
> Add hardening measures on untar

- iocage_lib/ioc_start.py
- tests/data_classes.py
- tests/functional_tests/0004_start_test.py
Please merge #47 first.
----
Currently, iocage ignores IP addresses given for the loopback interface
lo0 that exists by default in a VNET jail. Adding addresses to that
interface can be useful, for instance to implement rfc7404 addressing
where link-local addresses are used for interconnections, and routable
addresses are set on loopback interfaces.
This commit enables setting additional addresses on the lo0 interface
using the usual ip4_addr or ip6_addr settings.
For instance: ip4_addr='lo0|192.168.2.10'
Closes https://github.com/freebsd/iocage/issues/46
> ioc_start.py: allow setting IP address on lo0

- iocage_lib/ioc_common.py
reorder code in `sort_releases()` to correctly detect `list -r` case
fix #50
> fix sort releases

- iocage_lib/ioc_fetch.py
In freebsd/iocage#49 a hardening measure was imported from truenas/iocage#358. This hardening measure limits what can be extracted (location and attributes). It is implemented by applying the 'tar' filter from tarfile. That filter does this[0]:
- Strip leading slashes (/ and os.sep) from filenames.
- Refuse to extract files with absolute paths (in case the name is absolute even after stripping slashes, e.g. C:/foo on Windows). This raises AbsolutePathError.
- Refuse to extract files whose absolute path (after following symlinks) would end up outside the destination. This raises OutsideDestinationError.
- Clear high mode bits (setuid, setgid, sticky) and group/other write bits (S_IWGRP | S_IWOTH).
While the first three modifications are desirable, the last one damages the extracted release …
> Fix hardening measure in release extraction

- setup.py
FreeBSD changed the location of man pages.
The current port has a patch to do this change.
> Update setup.py, new man page location

- iocage_lib/ioc_json.py
Otherwise, the uplink interface will be added to the bridge after updating iocage, which is functionally- as well as security-wise quite some headache.
Fixes #70
> Change 'vnet_default_interface' to match new reality

- iocage_lib/cache.py
used to destroy all jails with names starting like the one you destroy
now matching only name or name/*, not name*
fix #62
> correct jail name matching

- iocage_lib/ioc_start.py
could fix #66 the lazy way
just adding JID and JNAME vars available for exec_poststart
> add JID and JNAME vars for poststart script

- .github/workflows/test.yaml
Python 3.9 is long deprecated and isn't used in FreeBSD Ports for a while.
> CI: Remove Python 3.9 workflow

- iocage_lib/ioc_start.py
This was causing "iocage stop foo" to print a warning, which is then gets interpreted as error by iocage:
>   + Removing devfs_ruleset: 1000 OK
>   + Removing jail process FAILED:
> jail: the 'allow.dying' parameter and '-d' flag are deprecated and have no effect.
The jail man pages says about this argument:
> This is deprecated and has no effect.
> ioc_start.py: Stop passing allow.dying argument

- iocage.8
Document `/dev/null` option in `iocage(8)` manpage.
Closes #91
> iocage.8: document /dev/null option for resolver
